using APIService.DALs;
using APIService.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace APIService
{
    public class AuthService
    {
        IUserDAL _dal;

        public AuthService()
        {
            _dal = new UsersDAL();
        }

        public AuthService(IUserDAL dal)
        {
            _dal = dal;
        }

        /// <summary>
        /// Takes in a username and returns a list of all entries in the DB matching it, then checks checks if it is less
        /// than or equal to zero.
        /// </summary>
        /// <param name="username"></param>
        /// <returns>
        /// boolean result of comparing the count of the users list less than or equal to zero
        /// </returns>
        public bool UsernameExist(string username)
        {
            var users = _dal.GetByUsername(username);
            return users.Count <= 0;
        }

        /// <summary>
        /// Makes a call to insert the provided user into the database using the UsersDAL
        /// </summary>
        /// <param name="model"></param>
        /// <returns>
        /// The guid generated by the user being entered into the database
        /// </returns>
        public Guid AddUser(UserRecordModel model)
        {
            return _dal.InsertUser(model);
        }

        /// <summary>
        /// Checks that the provided username and password match a account in the database
        /// </summary>
        /// <param name="username"></param>
        /// <param name="password"></param>
        /// <returns>returns the id of the user that requested to login</returns>
        public string ValidLogin(string username, string password)
        {
            var users = _dal.GetByUsername(username);
            if(users.Count <= 0)
            {
                //No user with that username is registered
                return string.Empty;
            }

            if (Utilities.HashUtil.CheckPassword(password,users[0].Salt, users[0].Password))
            {
                return users[0].Id.ToString();
            }
            else
            {
                return string.Empty;
            }
        }
    }
}
